open Alcotest

module RustMain = Rust.Main
module RustUtils = Rust.Utils

(* Parse ATD source text as the module [name] (taken from the file name, like the pipeline) *)
let module_of name content =
  let file = Filename.concat (Filename.get_temp_dir_name ()) (name ^ ".atd") in
  let oc = open_out file in
  output_string oc content;
  close_out oc;
  let _, body = RustUtils.parse_atd_file file in
  Sys.remove file;
  (file, body)
;;

let generate modules = RustMain.generate_rust modules

let find_file files name =
  match List.find_opt (fun (f : Rust.Types.rs_file) -> f.name = name) files with
  | Some f -> f.content
  | None -> failf "no generated file %s" name
;;

let contains s sub =
  let n = String.length s and m = String.length sub in
  let rec go i = i + m <= n && (String.sub s i m = sub || go (i + 1)) in
  go 0
;;

let check_has msg content sub =
  if not (contains content sub)
  then failf "%s: expected to find %S in:\n%s" msg sub content
;;

let check_lacks msg content sub =
  if contains content sub then failf "%s: did not expect %S in:\n%s" msg sub content
;;

let test_record_fields () =
  let files =
    generate
      [ module_of
          "sample"
          {|
type sample <rs name="Renamed"> = {
  id: string;
  kind <json name="type">: string;
  loop: int;
  ?note: string option;
  tags: string list;
  secret <rs ignore="true">: string;
}
|}
      ]
  in
  let c = find_file files "sample" in
  check_has "struct renamed" c "pub struct Renamed {";
  check_has "json rename" c "#[serde(rename = \"type\")]\n    pub kind: String,";
  check_has "keyword escaped" c "pub r#loop: i64,";
  check_has "optional field" c
    "#[serde(default, skip_serializing_if = \"Option::is_none\")]\n    pub note: Option<String>,";
  check_has "list" c "pub tags: Vec<String>,";
  check_lacks "ignored field" c "secret";
  check_has "header" c "auto-generated by the fey-data OCaml pipeline"
;;

let test_unit_enum () =
  let files =
    generate [ module_of "sample" "type target = [ Self | Ally | None ]\n" ]
  in
  let c = find_file files "sample" in
  check_has "derives" c "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]";
  check_has "Self renamed" c "#[serde(rename = \"Self\")]\n    Self_,";
  check_has "plain variant" c "    Ally,\n"
;;

let test_payload_sum_uses_atd_encoding () =
  let files =
    generate
      [ module_of
          "sample"
          {|
type a = { x: int }
type b = { y: string }
type u = [ A of a | B of b | Nothing ]
|}
      ]
  in
  let c = find_file files "sample" in
  check_has "enum" c "pub enum U {\n    A(A),\n    B(B),\n    Nothing,\n}";
  check_has "tagged serialize" c "runtime::serialize_tagged(serializer, \"A\", payload)";
  check_has "unit serialize" c "U::Nothing => serializer.serialize_str(\"Nothing\")";
  check_has "tagged parse" c "runtime::parse_tagged(value)";
  check_has "payload arm" c "(\"B\", Some(payload)) => runtime::from_payload(payload).map(U::B)";
  check_has "unit arm" c "(\"Nothing\", None) => Ok(U::Nothing)";
  check_has "no serde derive on the enum" c "#[derive(Debug, Clone, PartialEq)]\npub enum U {"
;;

let test_type_field_adapter () =
  let files =
    generate
      [ module_of
          "sample"
          {|
type a = { kind <json name="type">: string }
type u = [ A of a ] <json adapter.ocaml="Atdgen_runtime.Json_adapter.Type_field">
|}
      ]
  in
  let c = find_file files "sample" in
  check_has "type field serialize" c "runtime::serialize_type_field(serializer, \"A\", payload)";
  check_has "type field parse" c "runtime::parse_type_field(value)"
;;

let test_recursion_is_boxed () =
  let files =
    generate
      [ module_of
          "sample"
          {|
type node = { name: string; child: tree; kids: tree list }
type tree = [ Leaf | Node of node ]
|}
      ]
  in
  let c = find_file files "sample" in
  check_has "inline recursion boxed" c "pub child: Box<Tree>,";
  check_has "list needs no box" c "pub kids: Vec<Tree>,";
  check_has "variant payload boxed" c "Node(Box<Node>),"
;;

let test_imports_resolve_across_modules () =
  let files =
    generate
      [ module_of "common" "type metadata = { title: string }\n";
        module_of
          "skill"
          {|
type metadata <ocaml from="Common"> = abstract
type skill = { metadata: metadata }
|}
      ]
  in
  let c = find_file files "skill" in
  check_has "import" c "use super::common::Metadata;";
  check_has "field type" c "pub metadata: Metadata,";
  check_lacks "abstract not emitted" c "pub struct Metadata";
  let m = find_file files "mod" in
  check_has "mod lists common" m "pub mod common;";
  check_has "mod lists skill" m "pub mod skill;";
  check_has "mod lists runtime" m "pub mod runtime;"
;;

let test_ints_are_lenient () =
  let files = generate [ module_of "sample" "type s = { n: int; ?m: int option; l: int list }\n" ] in
  let c = find_file files "sample" in
  check_has "int" c "deserialize_with = \"super::runtime::lenient_i64\"";
  check_has "option int" c "lenient_i64_option";
  check_has "int list" c "lenient_i64_vec"
;;

let test_runtime_is_emitted () =
  let files = generate [ module_of "sample" "type s = { n: string }\n" ] in
  let r = find_file files "runtime" in
  check_has "tagged helper" r "pub fn serialize_tagged";
  check_has "type field helper" r "pub fn parse_type_field";
  check_has "option module" r "pub mod atd_option"
;;

let test_unresolved_type_fails () =
  match generate [ module_of "sample" "type s = { n: missing }\n" ] with
  | _ -> fail "expected a failure for an unresolved type"
  | exception Failure msg -> check_has "message" msg "unresolved type `missing`"
;;

let () =
  run
    "Rust generator"
    [ ( "types",
        [ test_case "record fields" `Quick test_record_fields;
          test_case "unit enum" `Quick test_unit_enum;
          test_case "ints are lenient" `Quick test_ints_are_lenient;
          test_case "recursion is boxed" `Quick test_recursion_is_boxed
        ] );
      ( "serde",
        [ test_case "payload sum uses atd encoding" `Quick test_payload_sum_uses_atd_encoding;
          test_case "type field adapter" `Quick test_type_field_adapter;
          test_case "runtime is emitted" `Quick test_runtime_is_emitted
        ] );
      ( "modules",
        [ test_case "imports resolve across modules" `Quick test_imports_resolve_across_modules;
          test_case "unresolved type fails" `Quick test_unresolved_type_fails
        ] )
    ]
;;
