(* The fixed helper module emitted next to the generated types: it implements the
   atdgen JSON conventions that plain serde derives do not cover. *)

let source =
  {rs|// This file is auto-generated by the fey-data OCaml pipeline.
// DO NOT MODIFY - Your changes will be overwritten on next generation.
//
// Helpers for the atdgen JSON conventions used by the generated types:
//   variant without payload   "Tag"
//   variant with payload      ["Tag", payload]
//   Type_field adapter        {"type": "Tag", ...fields}   (payload is the whole object)
//   `x : T option` field      "None" | ["Some", value]

use serde::de::Error as _;
use serde::ser::Error as _;
use serde::ser::SerializeTuple as _;
use serde::{Serialize, Serializer};
use serde_json::{Map, Value};

/// Writes a payload variant as `["Tag", payload]`.
pub fn serialize_tagged<S: Serializer, T: Serialize>(
    serializer: S,
    tag: &str,
    payload: &T,
) -> Result<S::Ok, S::Error> {
    let mut tuple = serializer.serialize_tuple(2)?;
    tuple.serialize_element(tag)?;
    tuple.serialize_element(payload)?;
    tuple.end()
}

/// Writes a payload variant of a `Type_field` sum: the payload object with `"type": tag` first.
pub fn serialize_type_field<S: Serializer, T: Serialize>(
    serializer: S,
    tag: &str,
    payload: &T,
) -> Result<S::Ok, S::Error> {
    match serde_json::to_value(payload).map_err(S::Error::custom)? {
        Value::Object(fields) => {
            let mut object = Map::with_capacity(fields.len() + 1);
            object.insert("type".to_owned(), Value::String(tag.to_owned()));
            for (key, value) in fields {
                if key != "type" {
                    object.insert(key, value);
                }
            }
            Value::Object(object).serialize(serializer)
        }
        other => other.serialize(serializer),
    }
}

/// Splits `"Tag"` / `["Tag", payload]` into the tag and the optional payload.
pub fn parse_tagged(value: Value) -> Result<(String, Option<Value>), String> {
    match value {
        Value::String(tag) => Ok((tag, None)),
        Value::Array(items) => {
            let mut items = items.into_iter();
            match (items.next(), items.next(), items.next()) {
                (Some(Value::String(tag)), payload, None) => Ok((tag, payload)),
                _ => Err("expected [\"Tag\", payload]".to_owned()),
            }
        }
        other => Err(format!("expected a variant, found {other}")),
    }
}

/// Splits `"Tag"` / `{"type": "Tag", ...}` into the tag and the optional payload (the whole object).
pub fn parse_type_field(value: Value) -> Result<(String, Option<Value>), String> {
    match value {
        Value::String(tag) => Ok((tag, None)),
        Value::Object(fields) => match fields.get("type") {
            Some(Value::String(tag)) => Ok((tag.clone(), Some(Value::Object(fields)))),
            _ => Err("expected a string \"type\" field".to_owned()),
        },
        other => Err(format!("expected a variant object, found {other}")),
    }
}

/// Deserializes a variant payload.
pub fn from_payload<T: serde::de::DeserializeOwned, E: serde::de::Error>(
    payload: Value,
) -> Result<T, E> {
    serde_json::from_value(payload).map_err(E::custom)
}

/// Error for a tag that does not exist or a payload that is missing/unexpected.
pub fn bad_variant<E: serde::de::Error>(type_name: &str, tag: &str) -> E {
    E::custom(format!("unknown or malformed variant `{tag}` for {type_name}"))
}

/// An int that atdgen (Yojson) also reads from a JSON string such as `"1"`.
#[derive(serde::Deserialize)]
#[serde(untagged)]
enum LenientInt {
    Int(i64),
    Text(String),
}

impl LenientInt {
    fn get<E: serde::de::Error>(self) -> Result<i64, E> {
        match self {
            LenientInt::Int(value) => Ok(value),
            LenientInt::Text(text) => text
                .trim()
                .parse()
                .map_err(|_| E::custom(format!("expected an integer, found \"{text}\""))),
        }
    }
}

/// `deserialize_with` for `i64` fields: accepts `1` and `"1"`, always serializes `1`.
pub fn lenient_i64<'de, D: serde::Deserializer<'de>>(deserializer: D) -> Result<i64, D::Error> {
    use serde::Deserialize as _;
    LenientInt::deserialize(deserializer)?.get()
}

/// `deserialize_with` for `Option<i64>` fields.
pub fn lenient_i64_option<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<i64>, D::Error> {
    use serde::Deserialize as _;
    Option::<LenientInt>::deserialize(deserializer)?
        .map(LenientInt::get)
        .transpose()
}

/// `deserialize_with` for `Vec<i64>` fields.
pub fn lenient_i64_vec<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Vec<i64>, D::Error> {
    use serde::Deserialize as _;
    Vec::<LenientInt>::deserialize(deserializer)?
        .into_iter()
        .map(LenientInt::get)
        .collect()
}

/// serde `with` module for a required `T option` field: "None" | ["Some", value].
pub mod atd_option {
    use super::*;
    use serde::{Deserialize, Deserializer};

    pub fn serialize<S: Serializer, T: Serialize>(
        value: &Option<T>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        match value {
            None => serializer.serialize_str("None"),
            Some(inner) => serialize_tagged(serializer, "Some", inner),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>, T: serde::de::DeserializeOwned>(
        deserializer: D,
    ) -> Result<Option<T>, D::Error> {
        let value = Value::deserialize(deserializer)?;
        match parse_tagged(value).map_err(D::Error::custom)? {
            (tag, None) if tag == "None" => Ok(None),
            (tag, Some(payload)) if tag == "Some" => from_payload(payload).map(Some),
            (tag, _) => Err(bad_variant("option", &tag)),
        }
    }
}
|rs}
;;
