(* ============================================================================ *)
(* TYPES                                                                       *)
(* ============================================================================ *)

(* A generated Rust source file (one per ATD module, plus the fixed runtime/mod files) *)
type rs_file =
  { name : string; (* file name without the .rs extension *)
    content : string
  }

(* One type definition of the ATD corpus, addressed by (module, ATD name) *)
type entry =
  { module_name : string; (* lowercase ATD module, e.g. "skill" *)
    atd_name : string; (* e.g. "skill_cost" *)
    rust_name : string; (* e.g. "SkillCost" *)
    expr : Atd.Ast.type_expr;
    annot : Atd.Ast.annot;
    import_from : string option (* Some "common" for `<ocaml from="Common"> = abstract` *)
  }

(* Everything the generators need to resolve names across modules *)
type context =
  { entries : (string * string, entry) Hashtbl.t;
    recursive : (string * string, (string * string) list) Hashtbl.t
        (* type -> inline-contained types that can reach it back (need a Box) *)
  }

let generated_comment_header =
  "// This file is auto-generated by the fey-data OCaml pipeline.\n\
   // DO NOT MODIFY - Your changes will be overwritten on next generation.\n"
;;
